# Generated by Django 3.1.2 on 2024-05-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
