# Generated by Django 3.1.2 on 2024-05-07 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_obra_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fechaCompra',
            field=models.DateField(default=datetime.datetime(2024, 5, 7, 0, 6, 36, 356616)),
        ),
    ]
