# Generated by Django 3.1.2 on 2024-05-07 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_compra_fechacompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='codigo',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fechaCompra',
            field=models.DateField(default=datetime.datetime(2024, 5, 7, 10, 34, 19, 962312)),
        ),
    ]
