# Generated by Django 3.1.2 on 2024-05-07 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240507_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 5, 7, 12, 10, 9, 974606)),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fechaCompra',
            field=models.DateField(default=datetime.datetime(2024, 5, 7, 12, 10, 9, 974606)),
        ),
        migrations.AlterField(
            model_name='obra',
            name='razonRechazo',
            field=models.CharField(default='NULL', max_length=40),
        ),
    ]
