# Generated by Django 5.0.6 on 2024-05-24 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_autentificacion_alter_compra_fechacompra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autentificacion',
            name='imagen',
            field=models.ImageField(null=True, upload_to='obra'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fechaCompra',
            field=models.DateField(default=datetime.datetime(2024, 5, 24, 19, 9, 50, 696458)),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 5, 24, 19, 9, 50, 694941)),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 5, 24, 19, 9, 50, 696458)),
        ),
    ]
