# Generated by Django 5.0.6 on 2024-05-25 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_imagen_autentificacion_imagenautentificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autentificacion',
            name='imagenAutentificacion',
            field=models.ImageField(blank=True, null=True, upload_to='obra'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fechaCompra',
            field=models.DateField(default=datetime.datetime(2024, 5, 25, 12, 30, 43, 518734)),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 5, 25, 12, 30, 43, 518734)),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 5, 25, 12, 30, 43, 518734)),
        ),
    ]
