# Generated by Django 5.0.6 on 2024-05-25 20:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_autentificacion_imagenautentificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreBanco', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCuenta', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='compra',
            name='fechaCompra',
            field=models.DateField(default=datetime.datetime(2024, 5, 25, 16, 7, 48, 397895)),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 5, 25, 16, 7, 48, 382214)),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 5, 25, 16, 7, 48, 382214)),
        ),
        migrations.CreateModel(
            name='DatosCooperativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCuenta', models.CharField(max_length=60)),
                ('NombreCliente', models.CharField(max_length=120)),
                ('Correo', models.CharField(max_length=60)),
                ('Direccion', models.CharField(max_length=60)),
                ('Telefono', models.CharField(max_length=60)),
                ('NroCuenta', models.CharField(max_length=20)),
                ('imagenCooperativo', models.ImageField(blank=True, null=True, upload_to='obra')),
                ('Banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipobanco')),
                ('TipoCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipocuenta')),
            ],
        ),
    ]
