# Generated by Django 5.0.6 on 2024-05-26 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_compra_fechacompra_alter_cuenta_fechaingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='fechaAprobada',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='fechaRechazada',
        ),
        migrations.AlterField(
            model_name='compra',
            name='fechaCompra',
            field=models.DateField(default=datetime.datetime(2024, 5, 25, 22, 24, 3, 794099)),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 5, 25, 22, 24, 3, 788071)),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 5, 25, 22, 24, 3, 793966)),
        ),
    ]
