# Generated by Django 5.0.6 on 2024-05-26 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_obra_fechaaprobada_remove_obra_fecharechazada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fechaCompra',
            field=models.DateField(default=datetime.datetime(2024, 5, 25, 22, 29, 15, 472468)),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 5, 25, 22, 29, 15, 472468)),
        ),
        migrations.AlterField(
            model_name='obra',
            name='NombreUsuario',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 5, 25, 22, 29, 15, 472468)),
        ),
    ]
