# Generated by Django 5.0.6 on 2024-06-12 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_compra_fechacompra_alter_cuenta_fechaingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='Cantidad',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='PrecioFinal',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='fechaCompra',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 12, 11, 55, 42, 191711)),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 12, 11, 55, 42, 192711)),
        ),
    ]
