# Generated by Django 5.0.6 on 2024-06-13 17:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_compra_cantidad_remove_compra_preciofinal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoCompraDescripcion', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 13, 13, 35, 29, 781900)),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 13, 13, 35, 29, 782899)),
        ),
        migrations.AddField(
            model_name='compra',
            name='estadoCompra',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.estadocompra'),
        ),
    ]
