# Generated by Django 5.0.6 on 2024-06-13 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_estadocompra_alter_cuenta_fechaingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fechaCompra',
            field=models.DateField(default=datetime.datetime(2024, 6, 13, 13, 48, 48, 241088)),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 13, 13, 48, 48, 239086)),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 13, 13, 48, 48, 240086)),
        ),
    ]
