# Generated by Django 5.0.6 on 2024-06-13 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_compra_usuario_alter_compra_fechacompra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='fechaCompra',
        ),
        migrations.AlterField(
            model_name='compra',
            name='Obra',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='compra',
            name='estadoCompra',
            field=models.CharField(default='Carrito', max_length=60),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 13, 14, 41, 50, 271092)),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 13, 14, 41, 50, 272098)),
        ),
    ]
