# Generated by Django 5.0.6 on 2024-06-13 18:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_compra_fechacompra_alter_compra_obra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='Obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.obra'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='estadoCompra',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 13, 14, 56, 24, 16290)),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 13, 14, 56, 24, 17299)),
        ),
    ]
