# Generated by Django 5.0.6 on 2024-06-13 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_compra_obra_alter_compra_estadocompra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='Obra',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 13, 15, 14, 43, 790181)),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime(2024, 6, 13, 15, 14, 43, 792191)),
        ),
    ]
